#!/bin/bash

echo -e "[ \033[32mOK\033[0m ] Done installing Domoleaf slave daemon"
sed -i 's/files dns/files mdns4_minimal \[NOTFOUND=return\] dns mdns4/g' /etc/nsswitch.conf
sed -i 's/files mdns4_minimal \[NOTFOUND=return\] dns/files mdns4_minimal \[NOTFOUND=return\] dns mdns4/g' /etc/nsswitch.conf

usermod -a -G dialout knxd

sed -i 's/#net.ipv4.ip_forward/net.ipv4.ip_forward/g' /etc/sysctl.conf
sed -i 's/net.ipv4.ip_forward = 0/net.ipv4.ip_forward = 1/g' /etc/sysctl.conf

if [ -f /etc/inittab ];
then
	sed -i 's/^T0:23:respawn:\/sbin\/getty -L ttyAMA0 115200 vt100/#T0:23:respawn:\/sbin\/getty -L ttyAMA0 115200 vt100/g' /etc/inittab
fi
if [ -f /boot/cmdline.txt ];
then
	sed -i 's/console=ttyAMA0,115200 //g' /boot/cmdline.txt
	sed -i 's/kgdboc=ttyAMA0,115200 //g' /boot/cmdline.txt
fi
pip3 install scapy-python3

#Init/Upgrade
python3 /usr/bin/glslave/glslave_postinst.py

#CRON
chmod +x /usr/bin/CronRefreshNetwork.py
chmod +x /usr/bin/CronSendAlive.py
chmod +x /usr/bin/CronSendTech.py

#KNXD
systemctl enable knxd
systemctl restart knxd

chmod +x /usr/bin/glslave.py
chmod +x /etc/init.d/glslave
systemctl enable glslave
systemctl start glslave
