#!/bin/bash

echo -e "[ \033[32mOK\033[0m ] Done installing Domoleaf slave daemon"
sed -i 's/files dns/files mdns4_minimal \[NOTFOUND=return\] dns mdns4/g' /etc/nsswitch.conf
sed -i 's/files mdns4_minimal \[NOTFOUND=return\] dns/files mdns4_minimal \[NOTFOUND=return\] dns mdns4/g' /etc/nsswitch.conf

usermod -a -G dialout knxd

sed -i 's/#net.ipv4.ip_forward/net.ipv4.ip_forward/g' /etc/sysctl.conf
sed -i 's/net.ipv4.ip_forward = 0/net.ipv4.ip_forward = 1/g' /etc/sysctl.conf

if [ -f /etc/inittab ];
then
	sed -i 's/^T0:23:respawn:\/sbin\/getty -L ttyAMA0 115200 vt100/#T0:23:respawn:\/sbin\/getty -L ttyAMA0 115200 vt100/g' /etc/inittab
fi
if [ -f /boot/cmdline.txt ];
then
	sed -i 's/console=ttyAMA0,115200 //g' /boot/cmdline.txt
	sed -i 's/kgdboc=ttyAMA0,115200 //g' /boot/cmdline.txt
fi
pip3 install scapy-python3

#Upgrade
if [ -f /etc/domoleaf/slave.conf.save ]; then 
	aes=$(grep "^aes=" /etc/domoleaf/slave.conf.save | cut -d = -f 2)
	rm /etc/domoleaf/slave.conf.save
else
	aes=`echo $RANDOM $RANDOM $RANDOM $RANDOM | (sha1sum && echo $RANDOM) | sha1sum | sed 's/  -//g'`
fi

sed -i "s/aes=domoleaf/aes=$aes/g" /etc/domoleaf/slave.conf

#KNXD
systemctl enable knxd
cp /etc/domoleaf/knxd.conf /etc/
systemctl start knxd

chmod +x /usr/bin/slave.py
chmod +x /etc/init.d/glslave
systemctl enable glslave
systemctl start glslave
