#!/bin/bash

echo -e "[ \033[33m..\033[0m ] Removing Domoleaf slave daemon..."

mv /etc/domoleaf/slave.conf /etc/domoleaf/slave.conf.save

#Conf
rm -f /etc/apt/sources.list.d/domoleaf.list
rm -f /etc/cron.d/glslave.cron
rm -f /etc/domoleaf/knxd.conf

rm -f /usr/bin/CronRefreshNetwork.py /usr/bin/glslave.py
rm -rf /usr/bin/glslave /usr/lib/domoleaf

rm -f /usr/bin/monitor_enocean
rm -f /usr/bin/monitor_knx
