#!/bin/bash

echo -e "[ \033[33m..\033[0m ] Removing Domoleaf slave daemon..."

mv /etc/domoleaf/slave.conf /etc/domoleaf/slave.conf.save

#Conf
rm -f /etc/cron.d/domoslave*

rm -f /usr/bin/CronRefreshNetwork.py
rm -f /usr/bin/CronSendAlive.py
rm -f /usr/bin/CronSendTech.py

rm -f /usr/bin/domoslave.py
rm -rf /usr/bin/domoslave /usr/lib/domoleaf

rm -f /usr/bin/monitor_enocean
rm -f /usr/bin/monitor_knx
