#!/bin/bash

echo -e "[ \033[33m..\033[0m ] Removing Domoleaf master daemon..."

#Conf file
cp /etc/domoleaf/master.conf /etc/domoleaf/master.conf.save

#Backup images
rm -rf /etc/domoleaf/custom
cp -r /etc/domoleaf/www/templates/default/custom /etc/domoleaf/

rm -f /etc/cron.d/glmaster*
rm -rf /etc/domoleaf/www
rm -rf /etc/domoleaf/sql
rm -f /init.d/glmaster
rm -f /etc/nginx/sites-available/domoleaf.conf
rm -rf /usr/bin/glmaster 
