#!/bin/bash

usermod -a -G dialout knxd

pip3 install scapy-python3

#Init/Upgrade
python3 /usr/bin/domoslave/domoslave_postinst.py

#CRON
chmod +x /etc/domoleaf/cron/Cron*.py

#KNXD
update-rc.d knxd defaults
update-rc.d knxd enable
service knxd restart

chmod +x /usr/bin/domoslave.py
update-rc.d domoslave defaults
update-rc.d domoslave enable
service domoslave start

echo -e "[ \033[32mOK\033[0m ] Done installing Domoleaf slave daemon"
