#!/bin/bash

echo -e "[ \033[33m..\033[0m ] Removing Domoleaf slave daemon..."

service domoslave stop

mv /etc/domoleaf/slave.conf /etc/domoleaf/slave.conf.save

#Conf
rm -f /etc/cron.d/domoslave*

rm -f /etc/domoleaf/cron/CronRefreshNetwork.py
rm -f /etc/domoleaf/cron/CronSendAlive.py
rm -f /etc/domoleaf/cron/CronSendTech.py

rm -f /usr/bin/domoslave.py
rm -rf /usr/bin/domoslave /usr/lib/domoleaf
rm -f /etc/init.d/domoslave

rm -f /usr/bin/monitor_enocean
rm -f /usr/bin/monitor_knx
