SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS optiondef;

CREATE TABLE `optiondef` (
  `option_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(63) DEFAULT NULL,
  `namede` varchar(63) NOT NULL DEFAULT '',
  `namees` varchar(63) NOT NULL DEFAULT '',
  `namefr` varchar(63) NOT NULL DEFAULT '',
  `nameit` varchar(63) NOT NULL DEFAULT '',
  PRIMARY KEY (`option_id`),
  KEY `name` (`name`),
  KEY `namede` (`namede`),
  KEY `namees` (`namees`),
  KEY `namefr` (`namefr`),
  KEY `nameit` (`nameit`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `optiondef` (`option_id`, `name`, `namede`, `namees`, `namefr`, `nameit`)
VALUES
	(6, 'Humidity', '', '', 'Hygrométrie', ''),
	(12, 'ON/OFF', '', '', 'ON/OFF', ''),
	(13, 'Varied', '', '', 'Varié', ''),
	(54, 'Up/Down', '', '', 'Montée/Descente', ''),
	(72, 'Temperature', '', '', 'Température', ''),
	(73, 'CO2', 'CO2', 'CO2', 'CO2', 'CO2'),
	(79, 'Brightness', '', '', 'Luminosité', ''),
	(92, 'Light', '', '', 'Lumineuse', ''),
	(96, 'Open/Close', '', '', 'Ouverture/Fermeture', ''),
	(97, 'Motion detection', '', '', 'Détection de mouvements', ''),
	(112, 'Infrared detection', '', '', 'Détection InfraRouge', ''),
	(113, 'UltraSonic detection', '', '', 'Détection UltraSonic', ''),
	(153, 'Current detection', '', '', 'Détection de courant', ''),
	(173, 'Rain', '', '', 'Pluie', ''),
	(174, 'Wind', '', '', 'Vent', ''),
	(181, 'Option 1', '', '', 'Option 1', ''),
	(182, 'Option 2', '', '', 'Option 2', ''),
	(189, 'Option 3', '', '', 'Option 3', ''),
	(191, 'Option 4', '', '', 'Option 4', ''),
	(195, 'Option 5', '', '', 'Option 5', ''),
	(196, 'Option 6', '', '', 'Option 6', ''),
	(197, 'Option 7', '', '', 'Option 7', ''),
	(198, 'Option 8', '', '', 'Option 8', ''),
	(199, 'Option 9', '', '', 'Option 9', ''),
	(355, 'JPG Image', '', '', 'Image JPG', ''),
	(356, 'MJPEG', '', '', 'MJPEG', ''),
	(357, 'Top', '', '', 'Haut', ''),
	(358, 'Bottom', '', '', 'Bas', ''),
	(359, 'Left', '', '', 'Gauche', ''),
	(360, 'Right', '', '', 'Droite', ''),
	(361, 'Home', '', '', 'Home', ''),
	(363, 'Play', '', '', 'Lecture', ''),
	(364, 'Pause', '', '', 'Pause', ''),
	(365, 'Stop', '', '', 'Stop', ''),
	(366, 'Next', '', '', 'Suivant', ''),
	(367, 'Previous', '', '', 'Précédent', ''),
	(368, 'Mute', '', '', 'Muet', ''),
	(371, 'Siren', '', '', 'Sirène', ''),
	(383, 'Volume', '', '', 'Volume', ''),
	(388, 'Setpoint temperature', '', '', 'Température de consigne', ''),
	(392, 'Red intensity', '', '', 'Varié Rouge', ''),
	(393, 'Green intensity', '', '', 'Varié Vert', ''),
	(394, 'Blue intensity', '', '', 'Varié Bleu', ''),
	(399, 'Energy', '', '', 'Énergie', ''),
	(400, 'Ventilation 0', '', '', 'Ventilation 0', ''),
	(401, 'Ventilation 1', '', '', 'Ventilation 1', ''),
	(402, 'Ventilation 2', '', '', 'Ventilation 2', ''),
	(403, 'Ventilation 3', '', '', 'Ventilation 3', ''),
	(404, 'Ventilation 4', '', '', 'Ventilation 4', ''),
	(405, 'Ventilation 5', '', '', 'Ventilation 5', ''),
	(406, 'Ventilation 6', '', '', 'Ventilation 6', ''),
	(407, 'Power', '', '', 'Puissance', ''),
	(408, 'Picture', '', '', 'Photo', ''),
	(410, 'White intensity', '', '', 'Varié Blanc', ''),
	(412, 'Comfort', '', '', 'Confort', ''),
	(413, 'Night', '', '', 'Nuit', ''),
	(414, 'Eco', '', '', 'Eco', ''),
	(415, 'Frost free', '', '', 'Hors gel', ''),
	(416, 'Comfort -1°C', '', '', 'Confort -1°C', ''),
	(417, 'Comfort -2°C', '', '', 'Confort -2°C', ''),
	(425, 'Auto', '', '', 'Auto', ''),
	(426, 'Heat', '', '', 'Chauffage', ''),
	(427, 'Morning Warmup', '', '', 'Préchauffage', ''),
	(428, 'Cool', '', '', 'Froid', ''),
	(429, 'Night Purge', '', '', 'Nettoyage', ''),
	(430, 'Precool', '', '', 'Pré-refroidissement', ''),
	(431, 'Off', '', '', 'Off', ''),
	(432, 'Test', '', '', 'Test', ''),
	(433, 'Emergency Heat', '', '', 'Chauffage rapide', ''),
	(434, 'Fan only', '', '', 'Ventilateur seulement', ''),
	(435, 'Free Cool', '', '', 'Restitution de froid', ''),
	(436, 'Ice', '', '', 'Froid intense', ''),
	(437, 'Channel 1', '', '', 'Canal 1', ''),
	(438, 'Channel 2', '', '', 'Canal 2', ''),
	(439, 'Channel 3', '', '', 'Canal 3', ''),
	(440, 'Channel 4', '', '', 'Canal 4', ''),
	(441, 'VOC', '', '', 'COV', ''),
	(442, 'Tilt', '', '', 'Inclinaison', ''),
	(443, 'Eject', '', '', 'Ejection', ''),
	(444, 'Button 0', '', '', 'Bouton 0', ''),
	(445, 'Button 1', '', '', 'Bouton 1', ''),
	(446, 'Button 2', '', '', 'Bouton 2', ''),
	(447, 'Button 3', '', '', 'Bouton 3', ''),
	(448, 'Button 4', '', '', 'Bouton 4', ''),
	(449, 'Button 5', '', '', 'Bouton 5', ''),
	(450, 'Button 6', '', '', 'Bouton 6', ''),
	(451, 'Button 7', '', '', 'Bouton 7', ''),
	(452, 'Button 8', '', '', 'Bouton 8', ''),
	(453, 'Button 9', '', '', 'Bouton 9', ''),
	(454, 'Button AV/TV', '', '', 'Bouton AV/TV', ''),
	(455, 'Red button', '', '', 'Bouton rouge', ''),
	(456, 'Green button', '', '', 'Bouton vert', ''),
	(457, 'Blue button', '', '', 'Bouton bleu', ''),
	(458, 'Yellow button', '', '', 'Bouton jaune', ''),
	(459, 'Top arrow', '', '', 'Flèche haut', ''),
	(460, 'Bottom arrow', '', '', 'Flèche bas', ''),
	(461, 'Left arrow', '', '', 'Flèche gauche', ''),
	(462, 'Right arrow', '', '', 'Flèche droite', ''),
	(463, 'Volume +', '', '', 'Volume +', ''),
	(464, 'Volume -', '', '', 'Volume -', ''),
	(465, 'Program +', '', '', 'Programme +', ''),
	(466, 'Program -', '', '', 'Programme -', ''),
	(467, 'Record', '', '', 'Enregistrer', ''),
	(468, 'Backspace', '', '', 'Retour arrière', ''),
	(469, 'Fast-forward', '', '', 'Avance rapide', ''),
	(470, 'OK button', '', '', 'Bouton OK', ''),
	(471, 'Open', '', '', 'Ouverture', ''),
	(472, 'Close', '', '', 'Fermeture', '');

SET FOREIGN_KEY_CHECKS=1;
